'use client';
import {useState} from 'react';
import {useRouter} from 'next/navigation';
import Link from 'next/link';
import {ArrowRight,Sparkles,Compass} from 'lucide-react';
import {Stars,Header,Footer} from './shell';
const prompts=['Moved to a different city','Followed my creative side','Said yes to that opportunity'];
const decisions=['What if I moved to Bali instead of staying where I am?','What if I became a photographer in Tokyo?','What if I accepted a different university offer?'];
export default function Home(){const [decision,setDecision]=useState('');const router=useRouter();return <div className="entry-page"><Stars/><Header/><main className="entry"><div className="eyebrow"><span className="little-star">✦</span> A SMALL DECISION. AN ENTIRELY DIFFERENT LIFE.</div><h1>Somewhere, you<br/>said <em>what if.</em></h1><p className="entry-sub">Explore the life you didn’t choose.</p><form className="portal-form" onSubmit={e=>{e.preventDefault();sessionStorage.setItem('elsewhere-fork',decision);router.push('/create')}}><label htmlFor="decision">Which decision would you change?</label><div className="portal-input"><Sparkles size={20}/><input id="decision" value={decision} maxLength={600} onChange={e=>setDecision(e.target.value)} placeholder="What if I left everything and started again?"/><button className="primary" type="submit">Enter this universe <ArrowRight size={18}/></button></div></form><div className="examples"><span>OR FOLLOW A POSSIBILITY</span><div>{prompts.map((p,i)=><button key={p} onClick={()=>setDecision(decisions[i])}>{p}<ArrowUpRightSmall/></button>)}</div></div><div className="demo-invite"><span className="demo-orbit"><Compass size={22}/></span><div><span className="micro">A LIFE ALREADY IN MOTION</span><Link href="/demo">A camera. A one-way ticket. Tokyo.<ArrowRight size={17}/></Link></div><Link className="demo-link" href="/demo">Explore the demo</Link></div></main><div className="entry-map" aria-hidden="true"><svg viewBox="0 0 1200 250"><defs><linearGradient id="line"><stop stopColor="#695586" stopOpacity="0"/><stop offset=".5" stopColor="#b397e2"/><stop offset="1" stopColor="#695586" stopOpacity="0"/></linearGradient></defs><path d="M0 180 190 120 340 150 545 80 760 130 930 50 1200 95 M545 80 680 235 880 190" fill="none" stroke="url(#line)"/>{[[190,120],[340,150],[545,80],[760,130],[930,50],[880,190]].map(([x,y],i)=><g key={x}><circle cx={x} cy={y} r={i===2?7:3} fill={i===2?'#d9c7ff':'#9481bc'}/><circle cx={x} cy={y} r={i===2?20:10} fill="none" stroke="#ac95d3" opacity=".25"/></g>)}</svg><span className="map-note">ONE CHOICE. INFINITE ECHOES.</span></div><Footer/></div>}
function ArrowUpRightSmall(){return <span aria-hidden="true">↗</span>}
