import { z } from 'zod';
export const answersSchema = z.object({name:z.string().trim().min(1).max(40),age:z.enum(['16–20','21–25','26–30','31–35','36+']),city:z.string().trim().min(1).max(80),field:z.string().trim().min(1).max(100),interests:z.string().trim().min(3).max(160).refine(s=>s.split(',').filter(x=>x.trim()).length===3,'Add exactly three interests, separated by commas.'),desire:z.string().trim().min(2).max(200),decision:z.string().trim().min(10).max(600),tone:z.enum(['Beautiful','Realistic','Chaotic','Bittersweet','Mysterious']),intensity:z.enum(['Close to reality','A major change','Completely unexpected'])});
export type Answers=z.infer<typeof answersSchema>;
const line=z.string().min(1).max(3000);
export const artifactSchema=z.object({type:z.enum(['boarding','message','journal','calendar','note']),title:line,content:line,from:line});
export const nodeSchema=z.object({id:line,year:z.number().int().min(1).max(5),title:line,location:line,age:line,mood:line,narrative:line,event:line,gain:line,sacrifice:line,artifact:artifactSchema});
export const storySchema=z.object({title:line,introduction:line,startingDecision:line,location:line,role:line,lifestyle:line,people:z.array(line).min(1).max(5),nodes:z.array(nodeSchema).length(5),positive:line,difficult:line,butterfly:line,mystery:line,reflection:line,question:line,turningPoint:z.number().int().min(1).max(4),branchOptions:z.array(line).length(2)}).superRefine((s,ctx)=>{if(new Set(s.nodes.map(n=>n.id)).size!==5||s.nodes.some((n,i)=>n.year!==i+1))ctx.addIssue({code:'custom',message:'Timeline must have five distinct, ordered yearly chapters.'});});
export type Story=z.infer<typeof storySchema>;
export type Chapter=z.infer<typeof nodeSchema>;
export type Branch={id:string,parentNodeId:string,choice:string,node:Chapter};
export type Universe={id:string;story:Story;branches:Branch[];source:string;saved:boolean;shareToken:string|null;createdAt:string};
export const demo:Story={title:'The light you almost missed',introduction:'In another life, you bought the one-way ticket. Tokyo didn’t change everything at once. It began with a camera, a missed train, and someone who noticed you noticing.',startingDecision:'What if I left everything and became a photographer in Tokyo?',location:'Tokyo, Japan',role:'Independent photographer',lifestyle:'Small rooms, early trains, long walks with no destination.',people:['Yuki — a print-shop owner who becomes your first collaborator','Ren — a neighbour who teaches you to slow down'],positive:'You learn to make a living from the way you see the world.',difficult:'Distance turns familiar friendships into conversations you keep postponing.',butterfly:'You miss the last train and photograph a shuttered bakery. The owner finds the print, reopens for one weekend, and meets the person who becomes her business partner.',mystery:'Someone keeps buying the same photograph at every exhibition. They never leave a name.',reflection:'You did not become someone else. You gave a quieter part of yourself more room. The life you left still matters; it just isn’t the only life you could have loved.',question:'Would you trade a place that feels like home for a chance to be seen?',turningPoint:3,branchOptions:['Take the exhibition in Berlin','Stay and open a studio with Yuki'],nodes:[
{id:'arrival',year:1,title:'A one-way kind of morning',location:'Shimokitazawa, Tokyo',age:'24',mood:'Hopeful, a little homesick',narrative:'Your first apartment fits a futon, a kettle, and the suitcase you haven’t unpacked. You work café shifts while learning enough Japanese to ask strangers for a portrait. On Sunday, Yuki at the print shop makes your first contact sheet. She circles one frame. “This one feels like you.” For the first time, the move feels like a beginning, not an escape.',event:'You sell your first print for ¥3,000.',gain:'The courage to call yourself a photographer.',sacrifice:'The comfort of already knowing how your days work.',artifact:{type:'boarding',title:'The ticket that started it',from:'Fictional travel memory · 14 April',content:'KUL → HND\nKuala Lumpur to Tokyo Haneda\nPASSENGER: ALEX · SEAT: 24A\nONE WAY · A WINDOW, PLEASE'}},
{id:'rain',year:2,title:'The city lets you in',location:'Yanaka, Tokyo',age:'25',mood:'Connected',narrative:'Ren takes you walking before the shops open. You photograph the same street through a whole rainy season. A small magazine buys six images, enough to replace the lens you borrowed. You miss a birthday back home because the assignment runs late. The congratulatory messages and the guilt arrive on the same evening.',event:'Your first editorial series is published.',gain:'A community that knows the work behind your photographs.',sacrifice:'Being there for the ordinary moments back home.',artifact:{type:'message',title:'A message after midnight',from:'Yuki · 00:17',content:'Yuki: I saw the magazine at the station. Bought three copies.\nYou: Three?\nYuki: One for the shop. One for you. One for when you forget this happened.'}},
{id:'exhibition',year:3,title:'A room full of almosts',location:'Koenji, Tokyo',age:'26',mood:'Proud, uncertain',narrative:'Twenty-two people come to your first exhibition. You know seventeen of them. Someone from a Berlin gallery leaves a card beside the visitors’ book. Meanwhile, Yuki asks whether you would share the empty studio upstairs. One offer means movement; the other means roots. Neither includes a guarantee.',event:'Two invitations arrive on the same day.',gain:'The freedom to make a choice that is genuinely yours.',sacrifice:'The idea that the right choice will feel obvious.',artifact:{type:'calendar',title:'Opening night',from:'Personal calendar · 18 October',content:'19:00–21:00 · A room full of almosts\nKoenji Community Gallery\nBring: prints, tape, something to wear.\nReminder: Twenty people is still a room full of people.'}},
{id:'bakery',year:4,title:'The small things return',location:'Sangenjaya, Tokyo',age:'27',mood:'Grounded',narrative:'You choose another year in Tokyo. An image you took after missing the last train reaches the woman who once owned the bakery in it. She reopens for a weekend and asks you to document it. The job pays less than a commercial shoot. You take it anyway. That weekend becomes the series you are proudest of.',event:'A forgotten photograph brings a bakery back to life.',gain:'A better measure of what meaningful work can be.',sacrifice:'A better-paid assignment and a month of financial ease.',artifact:{type:'journal',title:'On missing the train',from:'Notebook · page 84',content:'I used to think the important moments would announce themselves. Tonight it was a closed bakery and a train I didn’t catch. Four years ago, I would have called that a bad night.'}},
{id:'home',year:5,title:'A life, in your own light',location:'Tokyo, and sometimes home',age:'28',mood:'Bittersweet, at peace',narrative:'The studio is small, but it is yours two days a week. You book a longer visit home and turn down an assignment to keep it. Your work is steadier now; your doubts are quieter, not gone. At the latest show, someone buys the bakery print again. No name. You leave a note with the gallery, just in case they return.',event:'You build a rhythm that leaves room for both homes.',gain:'A life with enough space for the person you were.',sacrifice:'The fantasy that one place could give you everything.',artifact:{type:'note',title:'To the version who stayed',from:'Your other self · unsent',content:'You would have made a life there, too. I know that now. I hope you found people who notice the way you see things. I hope you kept the camera.\n— You, elsewhere'}}]};
export function localStory(a:Answers):Story {
 const s:Story=structuredClone(demo);const moving=/bali|tokyo|london|berlin|malaysia/i.exec(a.decision);const place=moving?moving[0].replace(/^./,c=>c.toUpperCase()):a.city;
 const photo=/photograph|camera/i.test(a.decision),restaurant=/restaurant|café|cafe|cook/i.test(a.decision),study=/universit|study|degree|offer/i.test(a.decision);
 const role=photo?'Independent photographer':restaurant?'Neighbourhood restaurant founder':study?'Student and part-time project assistant':'Independent creative';
 const project=photo?'a portrait series':restaurant?'a tiny supper club':study?'a student-led community project':`a small project built around ${a.interests.split(',')[0].trim()}`;
 s.title=restaurant?'A table for another life':photo?'The light you almost missed':study?'The offer you said yes to':'The shape of a different life';s.startingDecision=a.decision;s.location=place;s.role=role;s.lifestyle=`A changing routine in ${place}, with room for ${a.interests}.`;s.people=['Mika — a collaborator with a very different background','Sam — an old friend who keeps asking honest questions'];
 const tone={Beautiful:'Small kindnesses make the uncertainty easier to carry.',Realistic:'The budget is tight, and progress is slower than you hoped.',Chaotic:'A cancelled booking and a chance introduction rearrange the week.',Bittersweet:'Good news arrives on a day you wish you could share with home.',Mysterious:'An unsigned note arrives before you have told anyone your plans.'}[a.tone];
 s.introduction=`${a.name}, imagine the moment you said yes to this instead: “${a.decision}” Your days in ${a.city}, and your experience in ${a.field}, still travel with you. This is one invented possibility, shaped around your wish for ${a.desire.toLowerCase()}.`;
 const events=[`You make room for ${project}.`,`Your first collaboration finds a small audience.`,`Two invitations force you to choose a direction.`,`An early mistake unexpectedly helps someone else.`,`You set boundaries that make the new life sustainable.`];
 const narratives=[`You begin in ${place} with ${project}. Your background in ${a.field} helps with the parts you thought would be unfamiliar, but starting again costs more time than you expected. Mika offers help in exchange for a favour next month. ${tone}`,`A conversation about ${a.interests.split(',')[1]?.trim()} becomes your first collaboration. There is enough interest to continue, but not enough income to relax. Sam asks whether this is bringing you closer to ${a.desire.toLowerCase()}. You are not ready to answer. ${tone}`,`A paid opportunity elsewhere arrives just as Mika offers you a longer-term partnership. You cannot give both the attention they deserve. ${a.intensity==='Completely unexpected'?'An invitation to teach on a travelling workshop adds an entirely unplanned possibility.':a.intensity==='Close to reality'?`Keeping your connection to ${a.field} gives you a practical fallback.`:'Taking the opportunity would mean rebuilding your routine again.'} ${tone}`,`A forgotten piece of work reaches someone outside your circle. They use it to begin something of their own and invite you back to see it. The visit means declining better-paid work. You go, then spend the next month carefully watching your budget. ${tone}`,`You protect one day each week for ${a.interests.split(',')[2]?.trim()}. The work is steadier, though it is still not effortless. Sam visits and recognises both how you have changed and what you kept. Wanting ${a.desire.toLowerCase()} has become a practice, not a finish line. ${tone}`];
 s.nodes=s.nodes.map((n,i)=>({...n,id:`year-${i+1}`,location:place,age:`${a.age} at the fork · +${i+1} year${i?'s':''}`,mood:a.tone,narrative:narratives[i],event:events[i],artifact:[{type:'boarding',title:'A ticket to the beginning',from:'Fictional travel memory',content:`${a.city.toUpperCase()} → ${place.toUpperCase()}\nPASSENGER: ${a.name.toUpperCase()}\nA new routine. A bag full of familiar things.`},{type:'message',title:'Someone noticed',from:'Mika · 22:14',content:`Mika: Someone asked about ${project} today.\n${a.name}: Are you serious?\nMika: Yes. It’s small. It still counts.`},{type:'calendar',title:'The conversation you keep rehearsing',from:'Personal calendar · Year 3',content:'18:30 · Meet Mika\nDiscuss: stay and build together, or take the new opportunity.\nBring the budget. Be honest.'},{type:'journal',title:'The unexpected connection',from:'Notebook · Year 4',content:`I thought ${project} had disappeared without a trace. Today someone told me it made them begin. I had no idea.`},{type:'note',title:'To the version who stayed',from:`${a.name}, elsewhere · unsent`,content:`I still think about ${a.city}. About ${a.field}. About the way we wanted ${a.desire.toLowerCase()}. None of it was wasted. I hope you know that.`}][i] as Chapter['artifact']}));
 s.positive=`You make space for ${project} and for people who value it.`;s.difficult=`The transition puts pressure on your savings and your connection to ${a.city}.`;s.butterfly=`An abandoned early attempt at ${project} inspires a stranger to start their own project. They introduce you to your next collaborator.`;s.mystery='An unsigned note quotes something you wrote before the move. You still do not know who sent it.';s.reflection=`${a.name}, this imagined life makes room for ${a.desire.toLowerCase()}, but it still asks for patience and compromise. The decision changes your circumstances; it does not erase the parts of you that came before.`;s.branchOptions=['Take the opportunity elsewhere','Stay and build with Mika'];return storySchema.parse(s);
}
export function makeBranch(story:Story,index:number):Chapter {const take=index===0;return {id:`${story.nodes[story.turningPoint-1].id}-choice-${index}`,year:story.turningPoint+1,title:take?'The unfamiliar door':'The roots you choose',location:take?(story.location==='Tokyo, Japan'?'Berlin, Germany':'A new city'):story.location,age:story.nodes[story.turningPoint].age,mood:take?'Brave, unsettled':'Committed, uncertain',narrative:take?`You accept: ${story.branchOptions[0]}. The first month is lonely. Your earlier work opens one door, but your reputation does not follow you automatically. You call an old collaborator and admit you miss the ordinary days. By winter, a small commission lets you continue.`:`You choose: ${story.branchOptions[1]}. Staying feels less dramatic, but the commitment is real. Shared rent and difficult conversations replace the fantasy of effortless partnership. The first project runs late. The next one is better. You begin to trust a slower kind of progress.`,event:story.branchOptions[index],gain:take?'A wider circle and the chance to begin again.':'A deeper partnership and a place to belong.',sacrifice:take?'The community you had just begun to rely on.':'The unanswered question of the opportunity you declined.',artifact:{type:'note',title:'From the other branch',from:`Your alternate self · Year ${story.turningPoint+1}`,content:take?'I went. It was not immediately wonderful. That doesn’t mean it was wrong.':'I stayed. Some days I wonder. Most days, I open the door and get to work.'}};}
