import {z} from 'zod';
import {db,json,owner,pack,sameOrigin,failure} from '@/lib/server';
import {makeBranch,type Story} from '@/lib/story';
type Context={params:Promise<{id:string}>};
export async function GET(_r:Request,c:Context){try{const {id}=await c.params;const {row,user}=await owner(id);if(!row)return json({error:'This universe is private, expired, or no longer exists.'},404);return json({universe:await pack(row),signedIn:!!user});}catch(e){return failure(e)}}
export async function POST(r:Request,c:Context){try{sameOrigin(r);const {id}=await c.params;const {row,user}=await owner(id);if(!row)return json({error:'Universe not found.'},404);if(!user)return json({error:'Sign in to save your universe and keep its branches.',signIn:true},401);const input=z.object({action:z.enum(['save','share','private','branch']),choice:z.number().int().min(0).max(1).optional()}).safeParse(await r.json());if(!input.success)return json({error:'Choose a valid action.'},400);const {action,choice}=input.data;
if(action==='save'){await db().batch([db().prepare('INSERT INTO users(id,display_name,created_at) VALUES(?,?,?) ON CONFLICT(id) DO NOTHING').bind(user.userId,user.displayName,new Date().toISOString()),db().prepare('UPDATE universes SET user_id=?,guest_hash=NULL,saved=1,expires_at=NULL WHERE id=?').bind(user.userId,id)]);}
if(action==='share'||action==='private'){if(!row.saved)return json({error:'Save this universe before sharing it.'},400);await db().prepare('UPDATE universes SET share_token=? WHERE id=? AND user_id=?').bind(action==='share'?(row.share_token||crypto.randomUUID()+crypto.randomUUID()):null,id,user.userId).run();}
if(action==='branch'){if(choice===undefined)return json({error:'Select a branch.'},400);if(!row.saved)return json({error:'Save this universe before keeping a branch.'},400);const story=JSON.parse(row.story) as Story;const node=makeBranch(story,choice);await db().prepare('INSERT INTO branches(id,universe_id,parent_node_id,choice,node,created_at) VALUES(?,?,?,?,?,?) ON CONFLICT(universe_id) DO UPDATE SET choice=excluded.choice,node=excluded.node').bind(crypto.randomUUID(),id,story.nodes[story.turningPoint-1].id,story.branchOptions[choice],JSON.stringify(node),new Date().toISOString()).run();}
const next=await owner(id);return json({universe:await pack(next.row),signedIn:true});}catch(e){return failure(e)}}
export async function DELETE(r:Request,c:Context){try{sameOrigin(r);const {id}=await c.params;const {row,user}=await owner(id);if(!row)return json({error:'Universe not found.'},404);if(!user)return json({error:'Sign in to delete a saved universe.'},401);await db().batch([db().prepare('DELETE FROM branches WHERE universe_id=?').bind(id),db().prepare('DELETE FROM universes WHERE id=?').bind(id)]);return json({deleted:true});}catch(e){return failure(e)}}
